#!/bin/bash

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

if [ -f "$GITPOD_REPO_ROOT/.python-version" ]; then
    if [ $(cat "$GITPOD_REPO_ROOT/.python-version") != $(pyenv local)]; then
        pyenv install $(cat "$GITPOD_REPO_ROOT/.python-version")
    fi
fi

if [ -f "$GITPOD_REPO_ROOT/.venv" ]; then
    source "$GITPOD_REPO_ROOT/.venv/bin/activate"
fi